version: '3'
services:
  bot:
    build: .
    container_name: lacorbeille-discordbot
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    command: ["node", "main.js"]