name: Deploy to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install rsync and sshpass
      run: sudo apt-get update && sudo apt-get install -y rsync sshpass

    - name: Upload files via rsync
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" rsync -avz --delete --rsh="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ \
        ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:/home/lacorbeille/LaCorbeilleDiscordBOT